In [15]:
import glob
import numpy as np

import util

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
skeletons_dir = "/beegfs/qx244/ds/NTU/clapping/nturgb+d_skeletons_clapping/"

In [3]:
skeleton_files = glob.glob(skeletons_dir+'*.skeleton')

In [4]:
len(skeleton_files)

948

In [11]:
bodyinfo = util.read_skeleton_file(skeleton_files[0])

In [14]:
bodyinfo[3][0]['joints'][3]

{'x': -0.2590789,
 'y': 0.354061,
 'z': 3.024345,
 'depthX': 231.2159,
 'depthY': 166.9363,
 'colorX': 881.7238,
 'colorY': 415.3925,
 'orientationW': 0.0,
 'orientationX': 0.0,
 'orientationY': 0.0,
 'orientationZ': 0.0,
 'trackingState': 2}

In [45]:
scaled_joints = util.normalize_joints(bodyinfo[3][0]['joints'])

In [46]:
scaled_joints

[array([ 1.01418502, -0.03515617, -0.01462721]),
 array([ 0.5072867 , -0.0172493 , -0.01095043]),
 array([0., 0., 0.]),
 array([-0.25425628,  0.01243038, -0.00621752]),
 array([ 0.12112879, -0.08601413, -0.00399918]),
 array([ 0.55215914, -0.15309922, -0.02927752]),
 array([ 0.65985933, -0.1164082 ,  0.09669337]),
 array([ 0.71499355, -0.11158173,  0.11724602]),
 array([0.20576375, 0.06588319, 0.00045457]),
 array([0.63632548, 0.07717617, 0.01353395]),
 array([0.81926788, 0.06197619, 0.10625709]),
 array([0.88344753, 0.05550092, 0.13934097]),
 array([ 9.72627921e-01, -7.19042536e-02,  2.44316887e-17]),
 array([ 0.81324305, -0.12382671,  0.14818481]),
 array([ 1.37440426, -0.14235248,  0.15764839]),
 array([ 1.41397961, -0.14642005,  0.21960046]),
 array([ 1.00000000e+00, -3.05396109e-18,  1.22158443e-17]),
 array([0.93163793, 0.06179003, 0.12476645]),
 array([1.50057048, 0.01521043, 0.13643064]),
 array([1.53971237, 0.00946747, 0.19824453]),
 array([ 0.12716761, -0.00419416, -0.0039061